config/routes.rb
Rails.application.routes.draw do

 get '/' => 'events#home'
 get '/events' => 'events#index'
 post '/events' => 'events#create'
 get '/events/new' => 'events#new', as: :'new_event'
 get '/events/:id/edit' => 'events#edit', as: :'edit_event'
 get '/events/:id' => 'events#show', as: :'event' 
 patch '/events/:id' => 'events#update'
 put '/events/:id' => 'events#update'
 delete '/events/:id' => 'events#destroy'

    

   

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   def index
    @events = Event.all
   end

   def show
    @event = Event.find(params[:id])
   end
  
   def new
    @event = Event.new
   end
    
   def create 
    @event = Event.new(event_params)
     if @event.save
       redirect_to '/events'
     else
       render 'new'    
     end
    end
   
   def edit
    @event = Event.find(params[:id])
   end

   def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
     redirect_to '/events'
    else
     render 'edit'
    end
   end
 
   def destroy
    @event = Event.find(params[:id])
    @event.destroy
     redirect_to '/events'
    end   

   private
    def event_params
     params.require(:event).permit(:event,:venue,:start_date,:end_date,:description)
    end 
   
         
 
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%= link_to "Back","/events" %><br><br>
<%= form_for @event, url: event_path do |t| %>
<table>
 <tr>
  <th>Event</th>
  <th>Venue</th>
  <th>Start Time</th>
  <th>End Time</th>
  <th>Description</th> 
 </tr>   
 <tr>
  <td><%= t.text_field :event, :value => @event.event %></td>
  <td><%= t.text_field :venue, :value => @event.venue %></td>
  <td><%= t.date_field :start_date, :value => @event.start_date %></td>
  <td><%= t.date_field :end_date, :value => @event.end_date %></td>
  <td><%= t.text_area :description, :value => @event.description %></td>
  <td><%= t.submit "Update" %>
  </tr>
 </table>
<% end %>
 

app/views/events/home.html.erb
<h1>Welcome to the Events database</h1>
<h2>Choose an Option</h2>
<%= link_to "Display Events","/events" %><br><br>
<%= link_to "New Event","/events/new" %>

app/views/events/index.html.erb
<h1>Events</h1>
<%= link_to "New Event", "events/new" %><br><%= link_to "Back","/" %><br><br>
<table border="1">
 <tr>
  <th>ID</th>
  <th>Event</th>
  <th>Venue</th>
  <th>Start Time</th>
  <th>End Time</th>
  <th>Description</th> 
</tr> 

 <% @events.each do |t| %>
  <tr>
   <td><%= t.id %></td>
   <td><%= t.event %></td>
   <td><%= t.venue %></td>
   <td><%= t.start_date %></td>
   <td><%= t.end_date %></td>
   <td><%= t.description %></td>
   <td><%= link_to 'Show', event_path(t) %></td>
   <td><%= link_to 'Edit', edit_event_path(t) %></td>
   <td><%= link_to 'Delete', event_path(t), method: :delete, data: { confirm: 'Are you sure?' } %></td>
 </tr> 
 <% end %>
</table><br>

app/views/events/new.html.erb
<h1>New Event</h1>
<%= link_to "Back","/events" %><br><br>
<%= form_for(@event) do |t| %>
 <table>
  <tr>
    <th>Event</th>
    <th>Venue</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th>Description</th>          
   </tr> 
   <tr> 
    <td><%= t.text_field :event %></td>
    <td><%= t.text_field :venue %></td>
    <td><%= t.date_field :start_date %></td>
    <td><%= t.date_field :end_date %></td>
    <td><%= t.text_area :description %></td>
    <td><%= t.submit "Create" %></td>
   </tr>
 </table>
<% end %>

app/views/events/show.html.erb
<h1>Show</h1>

<table border="1">
 <tr>
  <th>ID</th>
  <th>Event</th>
  <th>Venue</th>
  <th>Start Time</th>
  <th>End Time</th>
  <th>Description</th> 
</tr> 

  <tr>
   <td><%= @event.id %></td>
   <td><%= @event.event %></td>
   <td><%= @event.venue %></td>
   <td><%= @event.start_date %></td>
   <td><%= @event.end_date %></td>
   <td><%= @event.description %></td>
  </tr> 

</table><br>


<%= link_to "Back", "/events" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Events</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>